FROM node:alpine

WORKDIR '/app'

COPY package.json .
RUN npm install

COPY . .

CMD ["npm", "run", "start"]

#docker run -p 3000:3000 -v /app/node_modules -v $(pwd):/app [imageid]
#docker build -f Dockerfile.dev .
#docker exec -it [container-id] npm run test